bind=SUPER+SHIFT,r,reload_config

bind=SUPER,d,spawn,rofi -show drun
bind=SUPER,Return,spawn,foot
bind=SUPER,e,spawn,thunar

bind=SUPER,m,quit
bind=SUPER,q,killclient,

bind=SUPER,Tab,focusstack,next
bind=SUPER,h,focusdir,left
bind=SUPER,l,focusdir,right
bind=SUPER,k,focusdir,up
bind=SUPER,j,focusdir,down

bind=SUPER+SHIFT,k,exchange_client,up
bind=SUPER+SHIFT,j,exchange_client,down
bind=SUPER+SHIFT,h,exchange_client,left
bind=SUPER+SHIFT,l,exchange_client,right

bind=SUPER,g,toggleglobal,
bind=ALT,Tab,toggleoverview,
bind=ALT,backslash,togglefloating,
bind=ALT,a,togglemaximizescreen,
bind=ALT,f,togglefullscreen,
bind=ALT+SHIFT,f,togglefakefullscreen,
bind=SUPER,i,minimized,
bind=SUPER,o,toggleoverlay,
bind=SUPER+SHIFT,I,restore_minimized
bind=ALT,z,toggle_scratchpad

bind=ALT,e,set_proportion,1.0
bind=ALT,x,switch_proportion_preset,
bind=alt+super+ctrl,Left,scroller_stack,left
bind=alt+super+ctrl,Right,scroller_stack,right
bind=alt+super+ctrl,Up,scroller_stack,up
bind=alt+super+ctrl,Down,scroller_stack,down

bind=alt+shift,Return,dwindle_toggle_split_direction

bind=SUPER,n,switch_layout

bind=SUPER,comma,viewtoleft,0
bind=CTRL,comma,viewtoleft_have_client,0
bind=SUPER,period,viewtoright,0
bind=CTRL,period,viewtoright_have_client,0
bind=CTRL+SUPER,Left,tagtoleft,0
bind=CTRL+SUPER,Right,tagtoright,0

bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

bind=Alt,1,tag,1,0
bind=Alt,2,tag,2,0
bind=Alt,3,tag,3,0
bind=Alt,4,tag,4,0
bind=Alt,5,tag,5,0
bind=Alt,6,tag,6,0
bind=Alt,7,tag,7,0
bind=Alt,8,tag,8,0
bind=Alt,9,tag,9,0

bind=alt+shift,Left,focusmon,left
bind=alt+shift,Right,focusmon,right
bind=SUPER+Alt,Left,tagmon,left
bind=SUPER+Alt,Right,tagmon,right

bind=ALT+SHIFT,X,incgaps,1
bind=ALT+SHIFT,Z,incgaps,-1
bind=ALT+SHIFT,R,togglegaps

# movewin
# bind=CTRL+SHIFT,Up,movewin,+0,-50
# bind=CTRL+SHIFT,Down,movewin,+0,+50
# bind=CTRL+SHIFT,Left,movewin,-50,+0
# bind=CTRL+SHIFT,Right,movewin,+50,+0

bind=CTRL+ALT,Up,resizewin,+0,-50
bind=CTRL+ALT,Down,resizewin,+0,+50
bind=CTRL+ALT,Left,resizewin,-50,+0
bind=CTRL+ALT,Right,resizewin,+50,+0

bind=SUPER,b,spawn,zen-browser

bind=SUPER,v,spawn_shell,cliphist list | rofi -dmenu | cliphist decode | wl-copy

bind=SUPER,t,spawn,change-theme -m
bind=SUPER,g,spawn,change-wallpaper -m

mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_middle,togglemaximizescreen,0
mousebind=SUPER,btn_right,moveresize,curresize

axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client

bind=SUPER,R,spawn,~/.config/waybar/scripts/reboot.sh
bind=SUPER,S,spawn,bash -c 'wayfreeze & PID=$!; sleep 0.1; AREA=$(slurp); [ -z "$AREA" ] && { kill $PID; exit 1; }; exec 3< <(grim -g "$AREA" -); kill $PID; satty --filename - <&3; exec 3<&-'

bind=,XF86AudioRaiseVolume,spawn,wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bind=,XF86AudioLowerVolume,spawn,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind=,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind=,XF86AudioMicMute,spawn,wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bind=,XF86MonBrightnessUp,spawn,brightnessctl -e4 -n2 set 5%+
bind=,XF86MonBrightnessDown,spawn,brightnessctl -e4 -n2 set 5%-
bind=,XF86AudioNext,spawn,playerctl next
bind=,XF86AudioPause,spawn,playerctl play-pause
bind=,XF86AudioPlay,spawn,playerctl play-pause
bind=,XF86AudioPrev,spawn,playerctl previous
