# More option see https://github.com/DreamMaoMao/mango/wiki/
source=./modules/look.conf
source=./modules/layouts.conf
source=./modules/overview.conf
source=./modules/misc.conf
source=./modules/input.conf
source=./modules/rules.conf
source=./modules/binds.conf
source=./modules/autostart.conf
source=./modules/env.conf
